name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up EdgeDB
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- -y
          edgedb server install

      - name: Create EdgeDB credentials directory
        run: mkdir -p /home/runner/.config/edgedb/cloud-credentials

      - name: Add EdgeDB secret key
        run: |
          echo '{"secret_key": "${{ secrets.EDGEDB_SECRET_KEY }}"}' > /home/runner/.config/edgedb/cloud-credentials/default.json

      - name: Initialize EdgeDB project
        run: edgedb project init --link --server-instance ${{ secrets.EDGEDB_INSTANCE }} --non-interactive
        env:
          EDGEDB_INSTANCE: ${{ secrets.EDGEDB_INSTANCE }}
          EDGEDB_SECRET_KEY: ${{ secrets.EDGEDB_SECRET_KEY }}

      - name: Build project
        run: npm run build
        env:
          EDGEDB_INSTANCE: ${{ secrets.EDGEDB_INSTANCE }}
          EDGEDB_SECRET_KEY: ${{ secrets.EDGEDB_SECRET_KEY }}

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
